name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  Docker-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u=$DOCKER_USER -p=$DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/gitops:$GITHUB_RUN_NUMBER
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USER }}/gitops:$GITHUB_RUN_NUMBER

  Update-Manifest:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    - uses: chrisdickinson/setup-yq@latest
    
  

    - name: switch directory 
      run: |
        git clone https://github.com/mani1soni/Kube-GitOps.git
        cd Kube-GitOps/nginx 
        yq w -i deployment.yml spec.template.spec.containers[0].image docker.io/${{ secrets.DOCKER_USER }}/gitops:$GITHUB_RUN_NUMBER
        cat deployment.yml
        ls -lrt
        git config --global user.name 'mani1soni'
        git config --global user.email 'manish.soni@8403@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/mani1soni/Kube-GitOps.git
        git commit -am "deployment updated"
        git push origin main
      
    
 
    
