name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u=$DOCKER_USER -p=$DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/gitops:$GITHUB_RUN_NUMBER
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USER }}/gitops:$GITHUB_RUN_NUMBER
      
    - name: clone kube repo
      run: git clone https://github.com/mani1soni/Kube-GitOps.git && cd Kube-GitOps/nginx
    - name: download yq
      run: wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && chmod +x /usr/bin/yq


